schema {
  mutation: RootMutationType
  query: RootQueryType
}

interface Node {
  "The ID of the object."
  id: ID!
}

type Country implements Node {
  "The ID of an object"
  id: ID!

  name: String!

  code: String!

  cities: [City!]!
}

type City implements Node {
  "The ID of an object"
  id: ID!

  name: String!

  slug: String!

  country: Country
}

type Sport implements Node {
  "The ID of an object"
  id: ID!

  name: String!

  slug: String!
}

type User implements Node {
  "The ID of an object"
  id: ID!

  name: String!

  surname: String!

  email: String!

  city: City

  defaultSport: Sport
}

type Media implements Node {
  "The ID of an object"
  id: ID!

  url: String

  mediaType: String

  filename: String

  position: Int
}

type Comment implements Node {
  "The ID of an object"
  id: ID!

  content: String
}

type Post implements Node {
  "The ID of an object"
  id: ID!

  caption: String

  sportId: ID

  cityId: ID

  insertedAt: DateTime

  media: [Media]

  comments: [Comment]

  likesCount: Int!

  likedByCurrentUser: Boolean

  user: User!
}

type PostConnection {
  pageInfo: PageInfo!
  edges: [PostEdge]
}

type LikePostPayload {
  post: Post!
}

type SportCityFeed implements Node {
  "The ID of an object"
  id: ID!

  sport: Sport!

  city: City!

  posts(after: String, first: Int, before: String, last: Int): PostConnection
}

type CreatePostPayload {
  postEdge: PostEdge!
}

type RootQueryType {
  node(
    "The ID of an object."
    id: ID!
  ): Node

  "Get all sports"
  allSports: [Sport!]!

  "Get all countries with their cities"
  countriesWithCities: [Country!]!

  "Get posts for a given city\/sport combination"
  postsByCityAndSport(citySlug: String, sportSlug: String): SportCityFeed!

  "Get current authenticated user"
  currentUser: User!
}

type RootMutationType {
  "Create a new post with optional media files"
  createPost(caption: String!, sportId: ID!, cityId: ID!, media: [Upload!]): CreatePostPayload

  "Updates user city"
  completeUserOnboarding(cityId: ID!, defaultSportId: ID!): User

  "Likes a post"
  likePost(id: ID!, doesLike: Boolean!): LikePostPayload

  "Soft delete a post"
  deletePost(id: ID!): Post!
}

"""
The `DateTime` scalar type represents a date and time in the UTC
timezone. The DateTime appears in a JSON response as an ISO8601 formatted
string, including UTC timezone ("Z"). The parsed date and time string will
be converted to UTC if there is an offset.
"""
scalar DateTime

"Represents an uploaded file."
scalar Upload

type PageInfo {
  "When paginating backwards, are there more items?"
  hasPreviousPage: Boolean!

  "When paginating forwards, are there more items?"
  hasNextPage: Boolean!

  "When paginating backwards, the cursor to continue."
  startCursor: String

  "When paginating forwards, the cursor to continue."
  endCursor: String
}

type PostEdge {
  node: Post
  cursor: String
}
