schema {
  mutation: RootMutationType
  query: RootQueryType
}

interface Node {
  "The ID of the object."
  id: ID!
}

type Country implements Node {
  "The ID of an object"
  id: ID!

  name: String!

  code: String!

  cities: [City!]!
}

type City implements Node {
  "The ID of an object"
  id: ID!

  name: String!

  slug: String!
}

type Sport implements Node {
  "The ID of an object"
  id: ID!

  name: String!

  slug: String!
}

type User implements Node {
  "The ID of an object"
  id: ID!

  name: String!

  surname: String!

  email: String!

  city: City

  defaultSport: Sport
}

type Media implements Node {
  "The ID of an object"
  id: ID!

  url: String

  mediaType: String

  filename: String

  position: Int
}

type Comment implements Node {
  "The ID of an object"
  id: ID!

  content: String
}

type Post implements Node {
  "The ID of an object"
  id: ID!

  caption: String

  userId: ID

  sportId: ID

  cityId: ID

  insertedAt: DateTime

  media: [Media]

  comments: [Comment]
}

type RootQueryType {
  "Get all sports"
  allSports: [Sport!]!

  "Get all countries with their cities"
  countriesWithCities: [Country!]!

  "Get posts for a given city\/sport combination"
  postsByCityAndSport(cityId: ID, sportId: ID): [Post!]!
}

type RootMutationType {
  "Create a new post with optional media files"
  createPost(caption: String!, userId: ID!, sportId: ID!, cityId: ID!, media: [Upload!]): Post

  "Updates user city"
  completeUserOnboarding(cityId: ID!, defaultSportId: ID!): User
}

"""
The `DateTime` scalar type represents a date and time in the UTC
timezone. The DateTime appears in a JSON response as an ISO8601 formatted
string, including UTC timezone ("Z"). The parsed date and time string will
be converted to UTC if there is an offset.
"""
scalar DateTime

"Represents an uploaded file."
scalar Upload
